
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.113.122.187:3306/linger_music
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.entity
  mapper-locations: classpath:mapper/*Dao.xml
server:
  port: 8888